CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(10)  NOT NULL,
    description VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS film (
    film_id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    description  VARCHAR(200) NOT NULL,
    mpa_id       INTEGER      NOT NULL REFERENCES mpa(mpa_id),
    release_date DATE         NOT NULL,
    duration     INTEGER      NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(50)  NOT NULL UNIQUE,
    login    VARCHAR(50)  NOT NULL,
    name     VARCHAR(100) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id  INTEGER REFERENCES film(film_id),
    genre_id INTEGER REFERENCES genre(genre_id),
    PRIMARY KEY(film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_like (
    film_id INTEGER REFERENCES film(film_id),
    user_id BIGINT  REFERENCES users(user_id),
    PRIMARY KEY(film_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_friend (
    user_id   BIGINT  REFERENCES users(user_id),
    friend_id BIGINT  REFERENCES users(user_id),
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(user_id, friend_id)
);

